# Training
seed: 42
epochs: 100
eta_min: 1.0e-6
batch_size: 8
weight_decay: 0.0
learning_rate: 1.0e-4
experiment_version: 1

# Model
num_classes: 10
dataset: cifar10
backbone: resnet50
freeze_encoder: False
random_weight_init: True